### ISSUE TITLE
Separate YAML Directory per course?

### ISSUE THREAD

**Issue by ryansb** [decause/hflossk#426]
Since this site is designed to support multiple courses, it may be best to separate out content that changes per course (static/books, student yaml files, etc) and have a git repo for yaml/data and a repo for code.

Alternative strategy would be to always cherry-pick code changes between courses, but that seems more tedious than necessary

cc: @decause @mansam

**Comment by decause** [comment]
Since .yaml is just flat text, I'm not worried about carrying around extra configs as much as I am worried about carrying around extra content. Perhaps in the site.yaml, we can directly point to each course's oer.yaml (i.e. hfoss-oer.yaml, advfoss-oer.yaml, etc...)?

This does add some extra bits to the repo, but it reduces the complexity of having git submodules, or other headaches with multiple repositories. The "all-in-one-easy-to-deploy-easy-to-learn" considerations trump the content modularity AFAIAC, but that's just my vote. I'm open to other suggestions.

@ryansb @mansam @ralphbean thoughts?

**Comment by ryansb** [comment]
I just meant to keep the module separated so it'd be possible to do something like:

```
pip install hflossk
git clone git@github.com/decause/hfoss-site.git
cd hfoss-site.git
hflossk site.yml
```

So the hfoss/advfoss -site repos would have content/yaml and hflossk would contain all the code and such. Though it is true that the comprehensibility bonus of the all-in-one repo is a big plus for the course.

**Comment by mansam** [comment]
I like Ryan's suggested approach here of having the courseware be an installable module that runs your course. It's true that the all-in-one-repo thing makes it easy to get the lay of the land, but it inextricably links the course to the courseware, and we've already seen how much fun it is to keep hflossk and advfoss in sync.

Having hflossk be a thing that you install with pip and just use to run a course site would be pretty sweet, because people can make PRs to the hflossk courseware independent of any particular class, and instructors would be able cart the content around and make changes independent of the code. It would also mean we could bundle some course generation tools (like are mentioned in #395) with the courseware module which currently don't make sense to bundle with hflossk-the-course-and-also-framework.

**Comment by decause** [comment]
@mansam and @ryansb though I _fully_ appreciate the spirit here (and the engineering rationale) for having content live separately (pip install hfoss-course would be _amazing_) this repository is meant to contain _all_ the things you need to take the course. 

The goal here (admittedly an entirely academic/pedagogical one) is that If a student was on a deserted island, but had the latest checkout of the repository, they could do all the required coursework without having access to the internet, until their battery died (and they hacked together a coconut-based solar charger Gilligan-Style.) 

I also understand it would also be "only one more git pull" to get ahold of the course content as well if it were a separate repository, but this has git-related complications of it's own (I've seen some pretty stellar gitastrophes on one repo, let alone multiple repos, or submodules.)

All that said, I'm still open. What does maintaining a sub-module look like? How does it change my README and deployment instructions? How many extra steps will this add to http://hfoss-fossrit.rhcloud.com/hw/firstflight? Don't forget, we gotta be able to do this on Mac/Win/GNU also.

I know one major benefit is that we'd reduce the repo size of hflossk significantly by removing the books/content. We'd still need to replace it with some dummy content for the resources.mak to not fail (I hacked around this by having placeholder .txt files in /static/books and /static/decks in the latest advfoss/prodstud.) Or better yet, we could make resources.mak not fail miserably if those dirs are empty :P

**Comment by ryansb** [comment]
That's actually the cool bit. No submodules. You'd have 3 repos for this fall.
- `decause/hflossk`, the flask biz
- `decause/hfoss`, the yaml and content for HFOSS
- `decause/advfoss`, the yaml and content for ADVFOSS

For the first flight instructions would need the repo name updated (from hflossk to the course-appropriate name) but the steps wouldn't really change otherwise.

Let's look at the use cases.

### Student wants to run the course locally for funsies
1. `git clone https://github.com/decause/hfoss-site.git`
2. `pip install hflossk`
3. Go to hfoss-site directory
4. Run `hflossk`
5. Go to `http://localhost:5000`

### Student wants to add some yaml/a book/a blog post/a homework assignment
1. `git clone git@github.com/STUDENT/hfoss-site.git # their fork`
2. Add content/yaml/whatever
3. `git push`
4. Pull request
5. TravisCI validates their change

### Student wants to fix a bug in hflossk
1. `git clone git@github.com/STUDENT/hflossk # their fork`
2. `python setup.py develop`
3. Make change
4. Go to the hfoss-site directory
5. Run `hflossk` to see their changes
6. (optional) test by running `tox`
7. `git push`
8. Pull request
9. TravisCI validates their change

**Comment by mansam** [comment]
To add on to Ryan's post, you would then have basically two upstreams.

First, you have `FOSSRIT/hflossk` which is the canonical source for the `hflossk` software. All the seriously mainstream bugfixes and features go there, which you are curating from profs all over.

For your classes, `decause/hflossk` would be the upstream for bugfixes and feature additions in the courseware. Other professors at other schools would do similar stuff, they'd have `randoprof/hflossk` and `mitprof/hflossk` and whatever that would be a relatively free-flowing upstream for their own classes.

So students can make PRs to the teacher's 'local' fork of `hflossk` and stuff can move fast and loose there, and then the really legit, best of the best stuff can get upstreamed from every professor's class to `FOSSRIT/hflossk` where it can be reviewed and eventually make it into a proper PyPI release.

## Workflow for a prof
1. Prof forks `FOSSRIT/hflossk` to `prof/hflossk`
2. Students fork `prof/hflossk`
3. Students make PR to `prof/hflossk` with some features and bugfixes
4. Prof makes pull requests to `FOSSRIT/hflossk` with widely useful stuff and bugfixes to be upstreamed
5. Remy accepts PRs into `FOSSRIT/hflossk` and releases to PyPI

**Comment by liam-middlebrook** [comment]
As a student who's taken HFOSS I think that this will ultimately be easier for students to manage and understand how to interact with the course repository. I know a few of the students last term were confused by directory structure, and I think that by keeping resources and student YAMLS in a separate repository from the site backend will make it easier for students to understand.

Also @decause this means that you won't have to make your clarification for the bugfix assignment, because students could fix a bug in hflossk, but not hfoss. :smiley_cat: Not to mention that the system that @mansam and @ryansb are suggesting would really help demonstrate the idea of what forks and upstream repositories really are to the students.

**Comment by ralphbean** [comment]
:+1:

**Comment by ryansb** [comment]
I've put together the `hflossk` CLI tool and a sample course (in this case it's just the content that was in hflossk before).

The changes: https://github.com/ryansb/hflossk/tree/theBigSplit (PR #427)
HFOSS course content: https://github.com/ryansb/hfoss-site

**Comment by liam-middlebrook** [comment]
I've put together what I think should be the final branches for the site

# Courseware:

## Branch:

https://github.com/liam-middlebrook/hflossk/tree/new-hflossk-final

## Pull Request:

https://github.com/decause/hflossk/pull/434

# Site Content:

## Branch:

https://github.com/liam-middlebrook/hfoss-site/tree/new-hfoss-site-final

## Pull Request:

https://github.com/ryansb/hfoss-site/pull/3

**Comment by ryansb** [comment]
:+1:

**Comment by ryansb** [comment]
Obsolete. See [ofcourse](https://github.com/ryansb/ofCourse).
