### ISSUE TITLE
Change the favicon

### ISSUE THREAD

**Issue by kocsenc** [decause/hflossk#433]
If we have a FOSS Icon it'd be awesome to put it up or even make one.
The current one seems to be the bootstrap default and we can do better!

For reference its under `hflossk/static/img`

Kocsen (HFOSS Class)

**Comment by liam-middlebrook** [comment]
As far as thinking of the future goes I'm going to look into having this as part of a YAML under the new hfoss-site format that @ryansb and I had set up over the summer.

Whether or not the actual favicon is changed is better left with someone with more art skills than myself.

**Comment by kocsenc** [comment]
Alright, so we can consider this taken care of on this "new format". We still need an image though, correct?!

**Comment by liam-middlebrook** [comment]
Yes, that is correct.

**Comment by kocsenc** [comment]
Ryan, why was this closed? Curious.

**Comment by ryansb** [comment]
Because while a favicon is still needed, the new image wouldn't be added here. It would be included in sites individually (see background). I thought it'd be best to open this issue on the site repo, so I closed this in the interim. Feel free to reopen if you disagree.

Background:
In the new format the code (e.g. `site.py`) will remain in hflossk but the content (images, templates, static content, etc) will be in "site" repositories (e.g. hfoss-site).

**Comment by decause** [comment]
If @kocsenc has a favicon now, I'd be happy to take one. Currently, there is some kind of silly error that comes up as "fav.ico.mak" that I wouldn't mind hunting down.

**Comment by ryansb** [comment]
Yeah, I know what that issue is. Where's the new favicon? I'll implement.

**Comment by decause** [comment]
@kocsenc did you ever send along a favicon?
@ryansb is this fixed in ofcourse upstream now?

If fixed, we should close this issue. If not fixed, we should migrate ticket to the proper repo.

**Comment by ryansb** [comment]
Favicon never received.

**Comment by ryansb** [comment]
Migrated
